 src/scripts/seedTechnieken.js
// Idempotent seeder: slaat over als collection al data bevat...
// ID = techniek naam lowercase, spaties → underscore, speciale tekens weg.

import { collection, getDocs, setDoc, doc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase';

const SEED_DATA = [
  {
    type: 'Val',
    techniek: 'Yoko-ukemi',
    basisvoorwaarden: ['Afslaan links rechts','Afslaan L +R met benen wisselen','Outen ukemi: 4punten, arm doorsteken','verste hand wegnemen: hoge 4puntensteun'],
    basisfase: ['vanuit stand','op knieën, partner meetrekken'],
    verdieping: ['Zijwaarts','hindernis: 4punten, achterwaarts','hindernis: 4punten, zijwaarts hand in kraag'],
    aandachtspunten: ['Op zij rollen','benen gespreid','voeten op de mat blijven','1 lijn'],
    remediering: ['naar hand kijken dat afklopt','kijk naar benen bij het rechtkomen','gordel onder de voet','mat/lijn gebruiken'],
    oefenvormen: ['hurkje, partner tikt schouder','Spiegelbeeld'],
    kyu_graden: ['6','5','4','3','2','1'],
    basis_vanaf_kyu: '6',
    verdieping_vanaf_kyu: '5',
  },
  {
    type: 'Val',
    techniek: 'Zempo-Kaiten',
    basisvoorwaarden: ['koprol (voor/achter)','koprol + rechtstaan'],
    basisfase: ['beginnen kioshi','start recht, blijven liggen','rechtstaan na val','verplaatsing'],
    verdieping: [],
    aandachtspunten: ['enkel over arm, schouden en rug','vermijden hielen op mat','benen niet kruisen','niet op zij rollen'],
    remediering: ['Pink contact mat, hoofd wegkijken','naar voeten kijken','goed afduwen'],
    oefenvormen: ['huppelen, op teken ushiro mawari sabaki + voet vooruit + val','touw over de mat'],
    kyu_graden: ['6','5','4','3','2','1'],
    basis_vanaf_kyu: '6',
    verdieping_vanaf_kyu: '5',
  },
  {
    type: 'Val',
    techniek: 'Ushiro-ukemi',
    basisvoorwaarden: ['koprol','schouderrol','liggend slaan','afslaan uit rol','hurk + afslaan'],
    basisfase: ['stand','achterwaartse verplaatsing','hindernis'],
    verdieping: [],
    aandachtspunten: ['hoofd niet tegen mat','kin bij borst','dicht bij hielen, bolle rug','afslaan scherpe hoek'],
    remediering: ['voorwerp onder kin','knieën met armen omsluiten','voelen wnr gordel mat raakt'],
    oefenvormen: ['ushiro mawari sabaki nadien val','duwen tegen handen (evenwichtspel)','over partner'],
    kyu_graden: ['6','5','4','3','2','1'],
    basis_vanaf_kyu: '6',
    verdieping_vanaf_kyu: '5',
  },
  {
    type: 'Val',
    techniek: 'mae-ukemi',
    basisvoorwaarden: ['plank'],
    basisfase: ['op knieën starten','kioshi (draai naar steunknie)'],
    verdieping: ['rechtstaand','na duw'],
    aandachtspunten: ['voorarm en handen afkloppen','buik geen contact','steun tenen'],
    remediering: ['aanduiden waar helper','vormspanning','naar tenen kijken'],
    oefenvormen: ['4 punten, benen naar achter','mountain climbers?','o uchi gari + plank','mexian wave'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },

  {
    type: 'houdgreep',
    techniek: 'Kuzure-kesa-gatame',
    basisvoorwaarden: ['Yoko-shiho-gatame','Shihopositie naar Kesa-positie','Positiewissels'],
    basisfase: ['1. Techniek','2. Verdedigen ebi + crossgrip','3. Uke ruglig & passeren: knie over been','4. Idem 3 met beenbevrijding','5. tori rug + kantel: 1 voet aan knie, andere knie doorsteken','6. 4 punten en kantel: kapitein haak'],
    verdieping: ['1. transitie, uke draait buik, kioshi rond','2. Transitie 4 punten: kapitein haak','3. Transitie o uchi, tussen been erover','4. Ontsnappen, crossgrip en omdraaien','5. Bevrijding: lange worst op brug','6. schakel: kuzure-kesa naar kesa-gatame'],
    aandachtspunten: ['linkerhand grijpt rechtermouw uke','rechterhand geen kledij vastnemen','rechterknie tegen rechterschouder','benen spreiden, L knie tegen mat','Hoofd beetje laag'],
    remediering: ['grijpen aan binennrijde rechterelleboog','enkel vingers tegen schouder','Uke toont contact','Controleren','Uke L been hoof raken'],
    oefenvormen: ['tegen elkaar benen gestrekt, afwisselnd gesa hodgreep, nadien randori','houdgreep, uke aanval of enkel ebi'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'houdgreep',
    techniek: 'Kesa-gatame',
    basisvoorwaarden: ['Kesa-positie innemen','Overstap vanuit stand','Overstap vanuit knielen'],
    basisfase: ['1. Techniek','2. Verdedigen ebi','3. Uke ruglig, knie over been','4. Knie over been: gaan en terugkeren','5. Uke zijlig: passeren','6. Vrije aanval + houdgreep'],
    verdieping: ['1. Transitie uke draait buik','2. Transitie 4 punten: over been','3. Transitie o uchi: tussen been','4. Ontsnappen: ebi + push away','5. Bevrijding: overbridge','6. Schakel kesa naar kuzure-kesa'],
    aandachtspunten: ['Tori dicht bij uke, heup dicht','hoofd laag aan schouder uke','Knie recht, voet plat','voet weg van uke'],
    remediering: ['Matje onder heup tori','lijn als gids','billen rollen, contact behouden'],
    oefenvormen: ['slalom: uke\'s rij, tori houdt na worp','randori houdgrepen'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },
  {
    type: 'houdgreep',
    techniek: 'Ushiro-kesa-gatame',
    basisvoorwaarden: ['Kesa-gatame','Kuzure-kesa-gatame'],
    basisfase: ['1. Techniek innemen','2. Verdedigen en bevrijden','3. Schakel vanuit kesa'],
    verdieping: ['Overgang kesa naar ushiro-kesa','Schakel met worp'],
    aandachtspunten: ['Beide handen vrij houden','Gewicht laag, heup dichtbij'],
    remediering: ['Positie aanwijzen met cones','Partner geeft feedback'],
    oefenvormen: ['Houdgreep wissel op signaal'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'houdgreep',
    techniek: 'Kata-gatame',
    basisvoorwaarden: ['Kesa-gatame','Draaien hoofd uke opzij'],
    basisfase: ['1. Techniek','2. Bevrijdingspoging uke','3. Schakel vanuit kesa-gatame'],
    verdieping: ['Transitie na worp','Variant met been'],
    aandachtspunten: ['Hoofd uke opzij','Elleboog uke dicht bij hals','Gewicht volledig op uke'],
    remediering: ['Sticker op mat voor elleboogplaatsing'],
    oefenvormen: ['Duo: 30s vasthouden, wissel'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'houdgreep',
    techniek: 'Yoko-shiho-gatame',
    basisvoorwaarden: ['Ruglig uke','Positie 4-punten tori'],
    basisfase: ['1. Techniek','2. Verdedigen brug','3. Knie over been','4. Passeren'],
    verdieping: ['Transitie vanuit worp','Bevrijding + aanval'],
    aandachtspunten: ['Handen ver over uke','Gewicht laag','Benen spreiden'],
    remediering: ['Mat aanwijzen voor handen','Gewicht oefenen op bag'],
    oefenvormen: ['Parcours: worp + houdgreep'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },
  {
    type: 'houdgreep',
    techniek: 'Kami-shiho-gatame',
    basisvoorwaarden: ['Yoko-shiho-gatame','Boven uke werken'],
    basisfase: ['1. Techniek','2. Verdediging brug','3. Passeerbewegingen'],
    verdieping: ['Kuzure-kami-shiho-gatame','Transitie'],
    aandachtspunten: ['Ellebogen tegen uke','Hoofd laag','Voeten ver'],
    remediering: ['Gewicht via kussen oefenen'],
    oefenvormen: ['Aanval van bovenaf na werp'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'houdgreep',
    techniek: 'Tate-shiho-gatame',
    basisvoorwaarden: ['Alle vorige houdgrepen','Rijden en stabiliseren'],
    basisfase: ['1. Techniek','2. Klem met benen','3. Brug en bevrijding'],
    verdieping: ['Schakel van/naar kami','Transitie worp-houdgreep'],
    aandachtspunten: ['Knieën tegen uke ribben','Handen diep','Heupen laag'],
    remediering: ['Oefenen op bag'],
    oefenvormen: ['Schakelrandori (alleen houdgrepen)'],
    kyu_graden: ['3','2','1'],
    basis_vanaf_kyu: '3',
    verdieping_vanaf_kyu: '2',
  },
  {
    type: 'houdgreep',
    techniek: 'Kuzure-kami-shiho-gatame',
    basisvoorwaarden: ['Kami-shiho-gatame'],
    basisfase: ['1. Techniek','2. Schakel kami naar kuzure-kami'],
    verdieping: ['Overgang + worp'],
    aandachtspunten: ['Één arm vrij laten','Controle aan kraag'],
    remediering: ['Stap-voor-stap inname positie'],
    oefenvormen: ['Duo houdgreeprandori'],
    kyu_graden: ['3','2','1'],
    basis_vanaf_kyu: '3',
    verdieping_vanaf_kyu: '2',
  },

  {
    type: 'Verplaatsing',
    techniek: 'ushiro-mawari-sabaki',
    basisvoorwaarden: ['Evenwicht op 1 been','Draaibewegingen'],
    basisfase: ['Staand draaien','Met stap achteruit','In verplaatsing'],
    verdieping: ['Koppelen aan val','Koppelen aan worp'],
    aandachtspunten: ['Voet niet kruisen','Hoofd omhoog','Snel, vloeiend'],
    remediering: ['Langzaam uitvoeren langs lijn','Ogen dicht'],
    oefenvormen: ['Slalomparcours + sabaki','Muziek: sabaki op beat'],
    kyu_graden: ['6','5','4','3','2','1'],
    basis_vanaf_kyu: '6',
    verdieping_vanaf_kyu: '5',
  },
  {
    type: 'Verplaatsing',
    techniek: 'Mae-mawari-sabaki',
    basisvoorwaarden: ['ushiro-mawari-sabaki'],
    basisfase: ['Staand','Met stap voorwaarts','In verplaatsing'],
    verdieping: ['Koppeling worp','Koppeling houdgreep'],
    aandachtspunten: ['Knie buigen bij draai','Stabiele landing'],
    remediering: ['Geleide beweging met partner'],
    oefenvormen: ['Parcours sabaki + worp'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },

  {
    type: 'Worpen',
    techniek: 'Seo nage',
    basisvoorwaarden: ['Kuzushi voorwaarts','Tsukuri draai','Kake'],
    basisfase: ['1. Techniek','2. In verplaatsing','3. Met verdediging uke'],
    verdieping: ['Links en rechts','Koppeling houdgreep','Schakel met andere worp'],
    aandachtspunten: ['Ellebogen dicht','Knieën buigen','Hoofd omhoog'],
    remediering: ['Oefenen aan muur','Uchi-komi band'],
    oefenvormen: ['Uchi-komi wandeling','Partner rand mat'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'Worpen',
    techniek: 'Tsurikomi-goshi',
    basisvoorwaarden: ['Kuzushi','Kraaggreep hoog','Heupplaatsing'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Nage-no-kata','Koppeling'],
    aandachtspunten: ['Kraag hoog trekken','Heup voor uke','Knie strekken bij worp'],
    remediering: ['Oefenen met gordel aan haak','Spiegelen'],
    oefenvormen: ['Nage-no-kata voorbereiding'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Tai-otoshi',
    basisvoorwaarden: ['Kuzushi voorwaarts-zijwaarts','Been uitstrekken'],
    basisfase: ['1. Techniek','2. In verplaatsing','3. Met weerstand'],
    verdieping: ['Links en rechts','Schakel ko-uchi + tai-otoshi'],
    aandachtspunten: ['Been gestrekt','Niet te dicht bij uke','Trek door'],
    remediering: ['Langzaam met partner','Uchi-komi gordel'],
    oefenvormen: ['Tai-otoshi poort (twee partners)'],
    kyu_graden: ['3','2','1'],
    basis_vanaf_kyu: '3',
    verdieping_vanaf_kyu: '2',
  },
  {
    type: 'Worpen',
    techniek: 'O-goshi',
    basisvoorwaarden: ['Kuzushi','Heupgreep','Draaien'],
    basisfase: ['1. Techniek','2. In beweging'],
    verdieping: ['Links en rechts','Koppeling o-uchi'],
    aandachtspunten: ['Heup volledig voor uke','Knie buigen','Trekken én draaien'],
    remediering: ['Heupplaatsing aan muur','Oefenen zonder greep'],
    oefenvormen: ['O-goshi estafette'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },
  {
    type: 'Worpen',
    techniek: 'uki-goshi',
    basisvoorwaarden: ['O-goshi','Kuzushi'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Variant met greep'],
    aandachtspunten: ['Heup deels voor uke','Mouw trekken'],
    remediering: ['Vergelijking met o-goshi'],
    oefenvormen: ['Vergelijkingsoefening o-goshi vs uki-goshi'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'Worpen',
    techniek: 'Koshi-geruma',
    basisvoorwaarden: ['O-goshi','Kraaggreep'],
    basisfase: ['1. Techniek'],
    verdieping: ['Links en rechts'],
    aandachtspunten: ['Arm over schouder','Heup contact'],
    remediering: ['Greep corrigeren met sticker'],
    oefenvormen: ['Koshi-serie (o-goshi, uki-goshi, koshi-geruma)'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'Worpen',
    techniek: 'O Soto Gari',
    basisvoorwaarden: ['Kuzushi achterwaarts','Beenbeweging'],
    basisfase: ['1. Techniek','2. In verplaatsing','3. Met verdediging'],
    verdieping: ['Links en rechts','Koppeling o-uchi'],
    aandachtspunten: ['Groot been naar achter','Borst op borst','Hoofd naast hoofd'],
    remediering: ['Oefenen aan muur','Langzaam contact been'],
    oefenvormen: ['O soto randori (enkel o-soto toegelaten)'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },
  {
    type: 'Worpen',
    techniek: 'O-uchi-gari',
    basisvoorwaarden: ['Kuzushi','Beenbeweging binnenkant'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Koppeling o-soto'],
    aandachtspunten: ['Been tot heup uke','Trekken en duwen gelijk'],
    remediering: ['Voet positie met tape'],
    oefenvormen: ['O-uchi + o-soto combinatie'],
    kyu_graden: ['5','4','3','2','1'],
    basis_vanaf_kyu: '5',
    verdieping_vanaf_kyu: '4',
  },
  {
    type: 'Worpen',
    techniek: 'Ko-uchi-gari',
    basisvoorwaarden: ['O-uchi-gari','Klein been'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Combinatie tai-otoshi'],
    aandachtspunten: ['Klein been maait','Voorwaartse kuzushi'],
    remediering: ['Tape op mat voor voetpositie'],
    oefenvormen: ['Ko-uchi + tai-otoshi schakel'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'Worpen',
    techniek: 'Ko-soto-gari',
    basisvoorwaarden: ['O-soto-gari','Klein been buiten'],
    basisfase: ['1. Techniek','2. Schakel met o-soto'],
    verdieping: ['Links en rechts'],
    aandachtspunten: ['Hiel uke','Zijwaarts kuzushi'],
    remediering: ['Voet target oefenen'],
    oefenvormen: ['Ko-soto poort'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
  {
    type: 'Worpen',
    techniek: 'Sasae-tsurikomi-ashi',
    basisvoorwaarden: ['Enkel plaatsing','Kuzushi voorwaarts'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Nage-no-kata'],
    aandachtspunten: ['Enkel voor scheenbeen uke','Vroeg blokkeren'],
    remediering: ['Stoel als hulpmiddel'],
    oefenvormen: ['Nage-no-kata voorbereiding'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Harai-goshi',
    basisvoorwaarden: ['O-goshi','Heupplaatsing','Beenveeg'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Nage-no-kata','Koppeling'],
    aandachtspunten: ['Been gestrekt bij veeg','Heup voor uke','Niet vallen'],
    remediering: ['Oefenen been veeg zonder partner'],
    oefenvormen: ['Harai estafette'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Hane-goshi',
    basisvoorwaarden: ['Harai-goshi','Springbeweging been'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Koppeling o-goshi'],
    aandachtspunten: ['Knie buigen, dan strekken','Explosief been'],
    remediering: ['Been oefening zonder partner'],
    oefenvormen: ['Hane vs harai vergelijking'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Uchi-mata',
    basisvoorwaarden: ['O-uchi-gari','Binnenkant been hoog'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Nage-no-kata','Koppeling'],
    aandachtspunten: ['Been in middel uke','Hoog zwaai','Heup rotatie'],
    remediering: ['Uchi-komi gordel'],
    oefenvormen: ['Uchi-mata circuit'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Hiza-guruma',
    basisvoorwaarden: ['Enkel/knie blokkade','Kuzushi zijwaarts'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts'],
    aandachtspunten: ['Blokkade op knie','Cirkelbewegingen handen'],
    remediering: ['Langzame verplaatsing met blokkade'],
    oefenvormen: ['Hiza-guruma slalom'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Ippon-seoi-nage',
    basisvoorwaarden: ['Seo nage','Elleboogcontrole'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Koppeling'],
    aandachtspunten: ['1 arm over','Elleboog hoog','Diep door knieën'],
    remediering: ['Oefenen aan muur','Uchi-komi'],
    oefenvormen: ['Seoi nage competitieoefening'],
    kyu_graden: ['3','2','1'],
    basis_vanaf_kyu: '3',
    verdieping_vanaf_kyu: '2',
  },
  {
    type: 'Worpen',
    techniek: 'Kata-guruma',
    basisvoorwaarden: ['Schouderplaatsing','Tillen'],
    basisfase: ['1. Techniek'],
    verdieping: ['Links en rechts','Varianten'],
    aandachtspunten: ['Laag door knieën','Uke op schouder','Snel optillen'],
    remediering: ['Oefenen met lichte partner'],
    oefenvormen: ['Kata-guruma estafette'],
    kyu_graden: ['2','1'],
    basis_vanaf_kyu: '2',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Okuri-ashi-harai',
    basisvoorwaarden: ['De-ashi-harai','Timing bij verplaatsing'],
    basisfase: ['1. Techniek in verplaatsing'],
    verdieping: ['Links en rechts','Nage-no-kata'],
    aandachtspunten: ['Beide enkels tegelijk','Timing is alles'],
    remediering: ['Langzame verplaatsing'],
    oefenvormen: ['Nage-no-kata voorbereiding'],
    kyu_graden: ['1'],
    basis_vanaf_kyu: '1',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'De-ashi-harai',
    basisvoorwaarden: ['Timing stap uke','Enkelblokkade'],
    basisfase: ['1. Techniek','2. In verplaatsing'],
    verdieping: ['Links en rechts','Koppeling'],
    aandachtspunten: ['Vroeg veeg','Platte voet bij veeg','Trekken en duwen'],
    remediering: ['Timing oefenen met metronoom'],
    oefenvormen: ['Ashi-waza spel'],
    kyu_graden: ['3','2','1'],
    basis_vanaf_kyu: '3',
    verdieping_vanaf_kyu: '2',
  },
  {
    type: 'Worpen',
    techniek: 'Tomoe-nage',
    basisvoorwaarden: ['Ruglig vallen','Voet in buik uke','Kuzushi voorwaarts'],
    basisfase: ['1. Techniek','2. Met verplaatsing'],
    verdieping: ['Links en rechts','Varianten'],
    aandachtspunten: ['Voet in navel','Trekken sterk','Benen strekken'],
    remediering: ['Oefenen op dikke mat'],
    oefenvormen: ['Tomoe-nage circuit'],
    kyu_graden: ['1'],
    basis_vanaf_kyu: '1',
    verdieping_vanaf_kyu: '1',
  },
  {
    type: 'Worpen',
    techniek: 'Tani-otoshi',
    basisvoorwaarden: ['Zijwaartse val','Achterwaartse beweging'],
    basisfase: ['1. Techniek'],
    verdieping: ['Links en rechts','Als counter'],
    aandachtspunten: ['Achteruit vallen','Been voor uke','Meeval'],
    remediering: ['Langzaam uitvoeren','Dikke mat'],
    oefenvormen: ['Tani-otoshi als verdediging'],
    kyu_graden: ['1'],
    basis_vanaf_kyu: '1',
    verdieping_vanaf_kyu: '1',
  },

  {
    type: 'Transitie',
    techniek: 'Transitie nage-waza naar katame-waza',
    basisvoorwaarden: ['Basisworpen','Basisgreep houdgrepen','Valtechnieken'],
    basisfase: ['Worp + direct houdgreep','Worp + uke draait = volgen','Worp + uke op 4 punten'],
    verdieping: ['Schakelrandori','Vaste combinaties (worp+houdgreep)','Vrije schakel randori'],
    aandachtspunten: ['Niet loslaten na worp','Positie bewaren','Snel reageren'],
    remediering: ['Slow motion schakel','Partner geeft feedback signaal'],
    oefenvormen: ['Transitieparcours','Schakelrandori met stopwatch'],
    kyu_graden: ['4','3','2','1'],
    basis_vanaf_kyu: '4',
    verdieping_vanaf_kyu: '3',
  },
];

// ── ID normalizer (consistent met stap 1 spec) ────────────────────────────────
function toId(name) {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

// ── Idempotent seed function ──────────────────────────────────────────────────
export async function seedTechnieken() {
  try {
    const snap = await getDocs(collection(db, 'technieken'));
    if (snap.size > 0) {
      console.log(`⛔ technieken collectie bevat al ${snap.size} docs — seeding overgeslagen`);
      return;
    }

    console.log('🚀 Start seeding technieken...');

    for (const t of SEED_DATA) {
      const id = toId(t.techniek);
      await setDoc(doc(db, 'technieken', id), {
        ...t,
        updatedAt: serverTimestamp(),
        updatedBy: 'seed',
      });
      console.log(`  ✓ ${t.techniek} → ${id}`);
    }

    console.log(`✅ ${SEED_DATA.length} technieken succesvol geseed`);
  } catch (error) {
    console.error('❌ Fout bij seeding technieken:', error);
    throw error;
  }
}
